version: '3'

services:
  springboot-docker-compose-app-container:
    image: java-springboot-port-adapter-pattern:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/springboot-docker-compose-app
    ports:
      - "8081:8080"