@startuml
hide empty description

[*] --> DRAFT
DRAFT : When user save the claim
DRAFT: or update the claim draft
SUBMITTED: when the claim is submitted and acknowledged
DISCARDED: when the claim is discarded
PENDING_SUBMISSION: When user submit the claim
SUBMISSION_ERROR: when the claim submission is failed
VERIFIED: when the claim is verified by eBenefit
DRAFT --> PENDING_SUBMISSION
PENDING_SUBMISSION --> SUBMITTED
DRAFT -> DISCARDED
PENDING_SUBMISSION -> DISCARDED
SUBMISSION_ERROR --> DISCARDED
SUBMISSION_ERROR <-- PENDING_SUBMISSION
SUBMISSION_ERROR -> PENDING_SUBMISSION
SUBMISSION_ERROR --> VERIFIED
DRAFT --> VERIFIED
DRAFT <-- DISCARDED
DRAFT <-- VERIFIED
@enduml